// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberInfo } from "./MemberInfo";

export interface AddMemberResult { add_members: Array<MemberInfo>, exist_members: Array<MemberInfo>, no_members: Array<number>, }