// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GroupInfo { id: number, uid: number, group_name: string, role: string | null, type: string, add_time: number, up_time: number, }