// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GroupAdd { group_name: string, group_desc: string, owner_uids: Array<number>, }