// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GroupUp { id: number, group_name: string | null, group_desc: string | null, }