// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberInfo } from "./MemberInfo";

export interface GroupWithMember { id: number, uid: number, group_name: string, group_desc: string, type: string, member: Array<MemberInfo>, }