// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface InterfaceInfo { id: number, uid: number, cat_id: number, project_id: number, title: string, method: string, path: string, status: string, api_opened: boolean, add_time: number, up_time: number, }