// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterfaceInfo } from "./InterfaceInfo";

export interface InterfaceMenu { id: number, uid: number, project_id: number, name: string, list: Array<InterfaceInfo>, add_time: number, up_time: number, }