// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReqBodyForm } from "./ReqBodyForm";
import type { ReqHeader } from "./ReqHeader";
import type { ReqParam } from "./ReqParam";
import type { ReqQuery } from "./ReqQuery";

export interface InterfaceUp { id: number, title: string | null, cat_id: number | null, method: string | null, path: string | null, tag: Array<string> | null, status: string | null, desc: string | null, markdown: string | null, req_params: Array<ReqParam> | null, req_headers: Array<ReqHeader> | null, req_query: Array<ReqQuery> | null, req_body_type: string | null, req_body_is_json_schema: boolean | null, req_body_form: Array<ReqBodyForm> | null, req_body_other: string | null, res_body_type: string | null, res_body_is_json_schema: boolean | null, res_body: string | null, api_opened: boolean | null, }