// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface InterfaceAdd { cat_id: number, title: string, method: string, path: string, }