// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface InterfaceCat { id: number, uid: number, index: number, name: string, project_id: number, desc: string, add_time: number, up_time: number, }