// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface MemberInfo { id: number, username: string, email: string, role: string, }