// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProjectAdd { name: string, group_id: number, basepath: string, desc: string, project_type: string, }