// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterfaceCat } from "./InterfaceCat";
import type { ProjectEnv } from "./ProjectEnv";

export interface ProjectDetail { id: number, uid: number, name: string, basepath: string, switch_notice: boolean, desc: string, group_id: number, project_type: string, color: string, icon: string, is_json5: boolean, is_mock_open: boolean, add_time: number, up_time: number, env: Array<ProjectEnv>, cat: Array<InterfaceCat>, }