// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProjectUp { id: number, name: string | null, group_id: number | null, basepath: string | null, desc: string | null, is_json5: boolean | null, switch_notice: boolean | null, project_type: string | null, }