// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NameValue } from "./NameValue";

export interface ProjectEnv { id: number, name: string, domain: string, header: Array<NameValue>, global: Array<NameValue>, }