// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ReqBodyForm { name: string, form_type: string, example: string, value: string, desc: string, required: boolean, }