// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ReqQuery { name: string, value: string, example: string, desc: string, required: boolean, }