// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserInfo { id: number, username: string, email: string, role: string, type: string, study: boolean, add_time: number, up_time: number, }