[package]
name = "yapi-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
validator = { version = "0.16.0", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1"